### PR TITLE
Create SOCIAL MECHANIC

### PR DESCRIPTION
**Pull request by MR-TAMIZHLAN-TEAM-NRD**

### CODE REVIEW

**Comment by ASTechnical** [comment]
Useless

**Comment by ASTechnical** [comment]
@Sumit9969 close this pull request, because it's useless.

**Comment by Sumit9969** [comment]
Wʜᴀᴛ ᴀʀᴇ ᴜ ᴅᴏɪɴɢ

**Comment by ASTechnical** [comment]
> Wʜᴀᴛ ᴀʀᴇ ᴜ ᴅᴏɪɴɢ

lmao

**Pull request closed without merging**
